DROP TABLE IF EXISTS event_votes;
DROP TABLE IF EXISTS votes_options;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS chat_users;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS chats;
DROP TABLE IF EXISTS groups;