CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER PRIMARY KEY,
    message TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notifications_types (
    notifications_id INTEGER PRIMARY KEY,
    message_user_id INTEGER,
    post_id_tag INTEGER,
    comment_reply_user_id INTEGER,
    follow_request_user_id INTEGER,
    follow_request_accept_user_id INTEGER,
    follow_user_id INTEGER,
    post_like_user_id INTEGER,
    post_dislike_user_id INTEGER,
    comment_like_user_id INTEGER,
    comment_mention_user_id INTEGER,
    post_mention_user_id INTEGER,
    group_invite_user_id INTEGER,
    group_join_user_id INTEGER,
    group_accept_user_id INTEGER,
    event_invite_user_id INTEGER,
    event_response_user_id INTEGER,
    FOREIGN KEY (notifications_id) REFERENCES notifications(id) ON DELETE CASCADE,
    FOREIGN KEY (message_user_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (post_id_tag) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (comment_reply_user_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (follow_request_user_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (follow_request_accept_user_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (follow_user_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (post_like_user_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (post_dislike_user_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (comment_like_user_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (comment_mention_user_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (post_mention_user_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (group_invite_user_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (group_join_user_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (group_accept_user_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (event_invite_user_id) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (event_response_user_id) REFERENCES user(id) ON DELETE CASCADE
);